### ISSUE TITLE
Image sometimes freeze....

### ISSUE THREAD

**Issue by Biomodder** [mfreiholz/ts3video#38]
Hi

I use this plugin talk to some people and sometimes the image freeze for 2 or 3 seconds, and back again....

This is normal? 

Tks for all

**Comment by mfreiholz** [comment]
Hi, well it might happens sometimes, but should not happen very often. It depends on the connection :-/

**Comment by Biomodder** [comment]
My connection is 30Download/3Upload, but happens with my friends who have 100Download/100Upload...

**Comment by mfreiholz** [comment]
I'm closing this issue, will be better with #54
