### ISSUE TITLE
API 21 For Teamspeak Client 3.1+ BETA

### ISSUE THREAD

**Issue by Bluscream** [mfreiholz/ts3video#40]
You already guessed it :P

**Comment by AstralDestiny** [comment]
Would love to see a working build for API 21. (Teamspeak Beta Client) I use the client for the Ipv6 Connections since Ipv6 connectivity is working in 3.1 .

**Comment by Bluscream** [comment]
API 21 is out of beta so it's time to release a update!

**Comment by chuckie1992** [comment]
Hi, i don't know if the latest version is for the 3.1 Stable release but i tried reinstalling it and the API says its still outdated while changelogs of version 10 says its updated version 8 only for the TS3 API but yet it doesn't work for me. Isn't it yet updated or something went wrong updating?

**Comment by mfreiholz** [comment]
Can't find the new SDK... Does anyone know where I can get it?
Maybe they made it "exclusive"? ...

**Comment by Bluscream** [comment]
You are funny :D

**Comment by mfreiholz** [comment]
I've created v0.11 which is compatible with TS 3.1.
Unfortunately Teamspeak3.1 release is getting rolled out very slowly. The guys decided that not everyone will get it at the same time, what is very bad for plugins. 

You need 
TS3VIDEO >= v0.6 for Teamspeak <= 3.1
TS3VIDEO >= v0.11 for Teamspeak >= 3.1

**Comment by Bluscream** [comment]
http://downloads.insanefactory.com/?file=ts3video/0.11/Conference_Client-0.11_Setup.exe
