### ISSUE TITLE
Open Source?

### ISSUE THREAD

**Issue by Galtrox** [mfreiholz/ts3video#44]
Will this be ever open source? 
Great Job chaps!

**Comment by mfreiholz** [comment]
Yes, probably as soon as I have time for the next update.

**Comment by Galtrox** [comment]
Great thank you, Keep up with the great work!

**Comment by mfreiholz** [comment]
Update..
I don't think the project is going to be open source soon (if at all).

**Comment by faflfama** [comment]
What made you change your opinion if I can ask?

**Comment by mfreiholz** [comment]
I'm thinking about selling the plugin (very cheap) in future.

**Comment by faflfama** [comment]
Thanks for the answer^^
