### ISSUE TITLE
The ordinal 4540 could not be located in the dynamic link library D:\SERVERS\xampp\php\ssleay32.dll

### ISSUE THREAD

**Issue by Bluscream** [mfreiholz/ts3video#45]
![image](https://cloud.githubusercontent.com/assets/3318223/21957751/62b95762-da9e-11e6-8c50-86e739c74c06.png)

**Comment by mfreiholz** [comment]
Looks like the installation tries to load the SSL lib from the wrong location :-/
Is your `D:\SERVER\xampp\php` on your $PATH variable?

**Comment by Bluscream** [comment]
yes

**Comment by mfreiholz** [comment]
Should be fixed since v0.12

**Comment by Bluscream** [comment]
yes it's working fine now, thanks :-)

**Comment by GskFID** [comment]
hi dube, i encountered this problem with openssl compiled by perl,but it's working fine with new installation downloaded from the official website, would you tell me how you fix that problem?
