### ISSUE TITLE
Zoom in and Out - bug

### ISSUE THREAD

**Issue by Miscni** [mfreiholz/ts3video#47]
We have been experience some problems with the Zoom.
When you zoom to much out, so pictures is larger then the full size window, or to much in so it is gone ,then it is not possibul to get the size back.

I would suggest, a simple function, that change webcam zoom size is set to a standard size.

And also lock the Camera Size for a certain size in small, and also have lock for the max size in zoom in.

**Comment by mfreiholz** [comment]
Good suggestions I will implement it. Thank you.

**Comment by Miscni** [comment]
Also the fix for reset the webcam, by going into regedit, is comfirmed, that 4 users and myself. got the webcam to work again :)
I'll suggest to add that to the documentation.

**Comment by mfreiholz** [comment]
Temporary workaround fix:
Use registry editor: CTRL+R and type `regedit`, Enter.
Delete this folder: `HKEY_CURRENT_USER\SOFTWARE\mfreiholz.de\Conference Client`

**Comment by mfreiholz** [comment]
Another note: Everytime when I "Maximize" the conference window on my Laptop, my video is black (might be a separate issue).

**Comment by Miscni** [comment]
one of the users we fixed the problem with, was haveing the same problem, but when we used the workaround fix, then the problem was fixed.

But maybe it is related. , I'll ask the rest of the laptop users, if they experience something like that.

**Comment by mfreiholz** [comment]
Fixed with 0.12
