### ISSUE TITLE
Video server considered ddos

### ISSUE THREAD

**Issue by fabricenl** [mfreiholz/ts3video#51]
The videoserver and connections to it are being grabbed by ddos filter. Good example is OVH which the game filter will fully stop people from connecting to the video server if the filter is on permanent. 

Anyway to resolve this or to have videoserver on a different server then the teamspeak server.

**Comment by fabricenl** [comment]
11 people, 9 video's on @ 720P causes the teamspeak and videoserver to lag. only thing going high is cpu which reaches 64%. Only thing I can think of is the ddos filter being a pain.

**Comment by mfreiholz** [comment]
Hm that is not good. Any suggestion what to do about it?

**Comment by fabricenl** [comment]
For us the solution is quite simple, we can host the videoserver on our other machine. But i don't think we can let teamspeak tell users what ip to connect to for the videoserver.

As for why its happening, I don't know, its weird.

**Comment by jedi404** [comment]
a solution would be to whitelist your domain and the port in whatever ip
filtering software you are using. ive seen this before with users that have
things like peerblock installed.

**Comment by fabricenl** [comment]
Had contact with the host, they also spoke with the datacenter guys that run it since they're responsible for the ddos filters. (Voxility).
Adjustments can't be made and they to find it strange that teamspeak spikes up to 80% of a core when the videoserver goes up. Why its caught by the ddos filter is also strange thing they'll look into more. 
They to advised putting videoserver on different machine then the teamspeak. So I think for the bigger users of the videoservers this might be a good solution. Like having a channel in teamspeak that has an ip in the description or so that will tell clients automatically what ip to connect to.

**Comment by mfreiholz** [comment]
I actually do have a routing-service. Each "TS3VIDEO -> Join" asks the routing-service where to connect. By defaults it answers with the source-teamspeak IP, but I do have the possibility to change it.

Idea: I could create some kind of user login, where everyone can register his videoserver setup his own routes.

I am also open for other solutions like a server-browser/-selection dialog after a click on *Join*.

**Comment by fabricenl** [comment]
Website is not a bad idea, I suppose with server query same kind of thing could be achieved using a channel or certain line of text in the default join channel that the client checks. 

In the end the easiest way is for the client to get that information from somewhere on the Teamspeak itself.

**Comment by mfreiholz** [comment]
The client shouldn't have to do anything with it, it should always be a matter of the administrator.

I will check the possibility to receive the channel description via plugin. I'm not sure whether this is possible.

**Comment by fabricenl** [comment]
But if the routing service already works, is it possible to have this done already? We shutdown our video servers tonight as our server choked

**Comment by mfreiholz** [comment]
Yes.. I can insert a route for you, if you want me to.

Mail me your public Teamspeak IP and DNS (optional) and the IP of the video server which should be used and I will setup the route for you.

info (at) mfreiholz (dot) de
