### ISSUE TITLE
Blackscreen on webcam (Solved)

### ISSUE THREAD

**Issue by Miscni** [mfreiholz/ts3video#60]
After updateing the Restrictubable drivers, the Plugin starts up correctly.
I can see everybody in the conference, except myself.

Running Windows 7 64-bit
8 GB Ram
Nvidia

When webcam is active, then I just get a black window. I cannot see myself, and nobody can see me. But they do see the blackscreen window, that schould show the webcam.

Both webcam are tested on various Webcam programs. And they are working.
Even testet on other computers with Teamspeak3 and they work fine.

Any ideas

**Comment by mfreiholz** [comment]
Hi Miscni.. to be honest.. I have no idea. Especially since the local video doesn't even use OpenGL acceleration, there is no special magic involved for the own picture. Did you make sure to select the correct webcam from list? No virtual, only the real physical webcam?

**Comment by Miscni** [comment]
Yep, even tryed to use 1 webcam at the time. So only 1 Webcam was plugedin.

Even tryed to clear regedit, just to be on the safe side. (But no luck either)
But I have to say, got 1 problem with installing Vcredist_arm.exe , getting win32 error.

When I get a fix for it, then I'll let you know, but it is some kind of weird behavior from somekind of software.

**Comment by Miscni** [comment]
Have narrowed it down, to some drivers issues on windows 7.
So the person who has the computer, has decided to upgrade.
I'll let you know, how things are turning out.

**Comment by Miscni** [comment]
Problem has been resolved. 
Windows 7 64-Bit had a Windows update, after that update, the webcam works like it schould.
But I have to suggest, that Minimum requeriments for the plugin : 4 GB of Ram. Windwos 7 64-bit is something that I would like to hear others with same specs, if they find it stable.
