### ISSUE TITLE
Switch to teamspeak's own filetransfer

### ISSUE THREAD

**Issue by Bluscream** [mfreiholz/ts3video#64]
It would be neat to use Teamspeaks live ft protocol for streaming
The stream could be chunked to prevent hdd flooding
The specialty about Teamspeak's FT is that others can already downloaded parts of the file that the uploader managed to upload already.

**Comment by mfreiholz** [comment]
I don't know the protocol. Is it based on TCP or UDP?

**Comment by Bluscream** [comment]
http://yat.qa/ressourcen/protokolle/#files


---
Sent from my Lenovo TAB 2 A10-70L running Android 6.0 via OctoDroid v4.2.1

**Comment by Miscni** [comment]
FileTransferProtocol is the FTP itself.
It might be possibul to use the FTP port for webcam, but I wouldn't suggest it.

**Comment by Bluscream** [comment]
I'm not talking about that. See one comment above yours.

**Comment by mfreiholz** [comment]
Even with this API, it is rather complicated and probably not as efficient as it is right now. There are much more possibilities with an own protocol+server-software.
