### ISSUE TITLE
Client 0.12 Resolutions issue

### ISSUE THREAD

**Issue by Miscni** [mfreiholz/ts3video#66]
First and foremost, the new update that has been made, are really nice.
Really like the idea, to switch between Videos and also see the names on each user, when seeing the on webcam. 

But but but,,,,

The new plugin for "certain" laptops with webcam and some variuos webcams, are only supporting certain resolutions.

(Client 0.12) 
The Resolutions that are shown : 160x120
						   176x144
						   320x240
						   352x288
						   640x480

Both camera and picture are in the same resolutions size. :(

But if we uninstall the new client.
And install the old one "Client 0.11", then it supports all the resolutions.

(Client 0.11)
The Resolutions that are shown :  160x120
						    176x144
						    320x240
						    352x288
						    640x480
						    752x416
						    800x600
						    960x720
						  1024x768
						  1184x656
						  1280x720
						 1600x1200
						 1920x1080
								
My guess is, that the new update (client 0.12), takes into account, what resolution your webcam "can" support.
If that is the case, is there anyway, that we can be giving control to the video, 
so we can see the users, with their original resolution.?

**Comment by mfreiholz** [comment]
Hi @Miscni 

that's right, the new version checks against the camera's capabilities.
What you're saying is, that the picture (aspect ratio) you see from other user is different based on resolution, right?

Thank you
Manuel

**Comment by mfreiholz** [comment]
I use the old way in 0.13 :)
