### ISSUE TITLE
2 Accounts plugin issue!! (Fixed)

### ISSUE THREAD

**Issue by Miscni** [mfreiholz/ts3video#68]
Okay here it is.
Been buggin me for a while now. And I am out of ideas!!!

I have this PC with Windows 10 Pro.

Main account is (Administrator)
Second accound is (Standard User)

Problem is, that the (standard user) cannot find the plugin? 
Plugin is being installed, but it is not being shown in Teamspeak 3 plugins.

Even tryed to install it from Administrator doesn't change a anything, 

But if I relog to Administrator, and start up Teamspeak 3 with TS3Video, then it functions like it should.
My guess is, that there is a permission problem with the plugin, when you have a Computer with multiply accounts.

**Comment by Bluscream** [comment]
Make sure the plugin is in 
```
C:\Users\<main account>\AppData\Roaming\TS3Client\TS3Video_<arch>.dll
```
AND
```
C:\Users\<second account>\AppData\Roaming\TS3Client\TS3Video_<arch>.dll
```

**Comment by Miscni** [comment]
I totally overlooked that options, Thx Bluescrem :)

I copyed the plugin to the other accounts folder, and now it works. :)
Thanks again 
Cheers

**Comment by Bluscream** [comment]
No problem :)

**Comment by Bluscream** [comment]
P.S. You might want to use the "Close Issue" button instead of renaming it :3

**Comment by Miscni** [comment]
Good idea :)
