### ISSUE TITLE
Update for newer Teamspeak Versions?

### ISSUE THREAD

**Issue by blakedj012** [mfreiholz/ts3video#91]
Do you work on that Plugin? It doesnt work with latest Teamspeak 3.5.

I hope you dont give up.

**Comment by dreia2k** [comment]
For me, it does run on 3.5.6.
Although I have installed it on a much earlier version of TeamSpeak which might have avoided the problem you are having...

What is your specific issue?

**Comment by mfreiholz** [comment]
Should work on current version.
Same question as @dreia2k :-)

Btw.. I do work on a complete rework of the plugin, but this takes a little bit more time :)

**Comment by blakedj012** [comment]
the plugin doenst show up in teamspeak

**Comment by mfreiholz** [comment]
> 
> 
> the plugin doesnt show up in teamspeak

Do you have administrator privileges during installation?

**Comment by blakedj012** [comment]
yes i use teamspeak x64 and administrator rights

**Comment by blakedj012** [comment]
it has worked with older versions of teamspeak

**Comment by mfreiholz** [comment]
Alright. I guess you did already try to install it again?

**Comment by blakedj012** [comment]
No i dont have this files in my pluginfolder.

**Comment by blakedj012** [comment]
The dll files are also not in the install folder of the program itself.

**Comment by blakedj012** [comment]
https://gyazo.com/c67a4310eb408b99b0b7bd6d9f5a1df9

I have rename the plugin file in the programm folder to zip and extract it to get the 2 dll files. After i put them into my ts3 plugin folder it shows this:

**Comment by blakedj012** [comment]
It worked now. On my other Computer it installs normal without Problems. And for me i must install the dll files manually.

**Comment by mfreiholz** [comment]
Alright, thanks for testing. I guess for some reason the installer couldn't overwrite the new DLLs.. or something :P
